Update docker-publish.yml

diff --git a/.github/workflows/docker-publish.yml b/.github/workflows/docker-publish.yml
--- a/.github/workflows/docker-publish.yml
+++ b/.github/workflows/docker-publish.yml
@@ -99,12 +99,12 @@ jobs:
     needs: [build]
     runs-on: ubuntu-latest
     steps:
-      - run: |
-          IMAGE_NAME_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
-          if docker run ${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}:latest | grep -q "container";
-          then echo "Test Passed"
-          else
-            echo "Test Failed"
-            exit 1
-          fi
+      - run: docker run ${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}:latest | grep "container" && "Test Passed"
+          # IMAGE_NAME_LOWER=$(echo "${{ env.IMAGE_NAME }}" | tr '[:upper:]' '[:lower:]')
+          # if docker run ${{ env.REGISTRY }}/${IMAGE_NAME_LOWER}:latest | grep -q "container";
+          # then echo "Test Passed"
+          # else
+          #   echo "Test Failed"
+          #   exit 1
+          # fi
    
